services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mirodageje-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Mirodageje_Db_2026!"
    ports:
      - "1433:1433"
